"""add_issuer_columns

Revision ID: 0d47509c5b51
Revises: 3f8a9b2c1d4e
Create Date: 2026-02-05 15:40:10.475742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d47509c5b51'
down_revision: Union[str, None] = '3f8a9b2c1d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('issuer_name', sa.String(length=255), nullable=False, server_default='Desconhecido'))
    op.add_column('invoices', sa.Column('issuer_cnpj', sa.String(length=14), nullable=False, server_default='00000000000000'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'issuer_cnpj')
    op.drop_column('invoices', 'issuer_name')
    # ### end Alembic commands ###
