"""Add invoice_processing table

Revision ID: 2da2e49a20cb
Revises: 54f4aa56c502
Create Date: 2026-02-05 13:39:19.850009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2da2e49a20cb'
down_revision: Union[str, None] = '54f4aa56c502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_processing',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('image_ids', sa.JSON(), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('sefaz_validated', sa.Boolean(), nullable=False),
    sa.Column('sefaz_data', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_processing_status'), 'invoice_processing', ['status'], unique=False)
    op.create_index(op.f('ix_invoice_processing_user_id'), 'invoice_processing', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_processing_user_id'), table_name='invoice_processing')
    op.drop_index(op.f('ix_invoice_processing_status'), table_name='invoice_processing')
    op.drop_table('invoice_processing')
    # ### end Alembic commands ###
