"""Add category_name and subcategory

Revision ID: 88011037c12d
Revises: 0d47509c5b51
Create Date: 2026-02-06 07:39:42.814997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88011037c12d'
down_revision: Union[str, None] = '0d47509c5b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('category_name', sa.String(length=100), nullable=True))
    op.add_column('invoice_items', sa.Column('subcategory', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_items', 'subcategory')
    op.drop_column('invoice_items', 'category_name')
    # ### end Alembic commands ###
